[32mINFO[0m:     [10-06-2024 21:31:19] Set chroma_server_nofile to 65535
[32mINFO[0m:     [10-06-2024 21:31:19] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [10-06-2024 21:31:19] Starting component System
[36mDEBUG[0m:    [10-06-2024 21:31:19] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [10-06-2024 21:31:19] Starting component SqliteDB
[36mDEBUG[0m:    [10-06-2024 21:31:19] Starting component QuotaEnforcer
[36mDEBUG[0m:    [10-06-2024 21:31:19] Starting component Posthog
[36mDEBUG[0m:    [10-06-2024 21:31:19] Starting component LocalSegmentManager
[36mDEBUG[0m:    [10-06-2024 21:31:19] Starting component SegmentAPI
[32mINFO[0m:     [10-06-2024 21:31:19] Started server process [[36m2522298[0m]
[32mINFO[0m:     [10-06-2024 21:31:19] Waiting for application startup.
[32mINFO[0m:     [10-06-2024 21:31:19] Application startup complete.
[31mERROR[0m:    [10-06-2024 21:31:19] [Errno 98] error while attempting to bind on address ('127.0.0.1', 8000): address already in use
[32mINFO[0m:     [10-06-2024 21:31:19] Waiting for application shutdown.
[36mDEBUG[0m:    [10-06-2024 21:31:19] Stopping component System
[36mDEBUG[0m:    [10-06-2024 21:31:19] Stopping component SegmentAPI
[36mDEBUG[0m:    [10-06-2024 21:31:19] Stopping component LocalSegmentManager
[36mDEBUG[0m:    [10-06-2024 21:31:19] Stopping component Posthog
[36mDEBUG[0m:    [10-06-2024 21:31:19] Stopping component QuotaEnforcer
[36mDEBUG[0m:    [10-06-2024 21:31:19] Stopping component SqliteDB
[36mDEBUG[0m:    [10-06-2024 21:31:19] Stopping component OpenTelemetryClient
[32mINFO[0m:     [10-06-2024 21:31:19] Application shutdown complete.
[32mINFO[0m:     [10-06-2024 21:33:46] Set chroma_server_nofile to 65535
[32mINFO[0m:     [10-06-2024 21:33:46] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [10-06-2024 21:33:46] Starting component System
[36mDEBUG[0m:    [10-06-2024 21:33:46] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [10-06-2024 21:33:46] Starting component SqliteDB
[36mDEBUG[0m:    [10-06-2024 21:33:46] Starting component QuotaEnforcer
[36mDEBUG[0m:    [10-06-2024 21:33:46] Starting component Posthog
[36mDEBUG[0m:    [10-06-2024 21:33:46] Starting component LocalSegmentManager
[36mDEBUG[0m:    [10-06-2024 21:33:46] Starting component SegmentAPI
[32mINFO[0m:     [10-06-2024 21:33:46] Started server process [[36m2527303[0m]
[32mINFO[0m:     [10-06-2024 21:33:46] Waiting for application startup.
[32mINFO[0m:     [10-06-2024 21:33:46] Application startup complete.
[32mINFO[0m:     [10-06-2024 21:33:46] Uvicorn running on [1mhttp://localhost:3000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [10-06-2024 21:34:29] ::1:60812 - "GET /docs HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 21:34:29] ::1:60812 - "GET /openapi.json HTTP/1.1" 200
[31mERROR[0m:    [10-06-2024 21:35:03] Collection test_collection does not exist.
Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 662, in get_collection
    await to_thread.run_sync(
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/api/segment.py", line 270, in get_collection
    raise ValueError(f"Collection {name} does not exist.")
ValueError: Collection test_collection does not exist.
[32mINFO[0m:     [10-06-2024 21:35:03] ::1:60816 - "GET /api/v1/collections/test_collection?tenant=default_tenant&database=default_database HTTP/1.1" 500
[31mERROR[0m:    [10-06-2024 22:03:41] Collection test_collection does not exist.
Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 662, in get_collection
    await to_thread.run_sync(
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/api/segment.py", line 270, in get_collection
    raise ValueError(f"Collection {name} does not exist.")
ValueError: Collection test_collection does not exist.
[32mINFO[0m:     [10-06-2024 22:03:41] ::1:46894 - "GET /api/v1/collections/test_collection?tenant=default_tenant&database=default_database HTTP/1.1" 500
[32mINFO[0m:     [10-06-2024 22:06:21] ::1:41328 - "GET /api/v1/count_collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:07:38] ::1:45212 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:07:38] ::1:45212 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:07:38] ::1:45224 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:07:41] ::1:45224 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[36mDEBUG[0m:    [10-06-2024 22:07:41] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [10-06-2024 22:07:41] ::1:45224 - "POST /api/v1/collections/36025c77-4d27-426b-9c6c-cecbddf4264b/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 22:08:18] ::1:36674 - "GET /api/v1/count_collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:09:30] ::1:45194 - "GET /api/v1/count_collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:09:40] ::1:35916 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:09:40] ::1:35916 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:09:40] Collection test_collection is not created.
[32mINFO[0m:     [10-06-2024 22:09:40] ::1:35930 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:09:43] ::1:35930 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:09:43] ::1:35930 - "POST /api/v1/collections/36025c77-4d27-426b-9c6c-cecbddf4264b/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 22:09:46] ::1:45194 - "GET /api/v1/count_collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:09:47] ::1:45194 - "GET /api/v1/count_collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[31mERROR[0m:    [10-06-2024 22:10:03] Database test_database not found for tenant default_tenant
Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 471, in get_database
    await to_thread.run_sync(
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/api/segment.py", line 131, in get_database
    return self._sysdb.get_database(name=name, tenant=tenant)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/db/mixins/sysdb.py", line 95, in get_database
    raise NotFoundError(f"Database {name} not found for tenant {tenant}")
chromadb.db.base.NotFoundError: Database test_database not found for tenant default_tenant
[32mINFO[0m:     [10-06-2024 22:10:04] ::1:45194 - "GET /api/v1/databases/test_database?tenant=default_tenant HTTP/1.1" 500
[32mINFO[0m:     [10-06-2024 22:10:20] ::1:45194 - "GET /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:11:45] ::1:53976 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:11:45] ::1:53976 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:11:45] ::1:53984 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:11:47] ::1:53984 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[36mDEBUG[0m:    [10-06-2024 22:11:47] Starting component PersistentLocalHnswSegment
[32mINFO[0m:     [10-06-2024 22:11:47] ::1:53984 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 22:11:52] ::1:51380 - "GET /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:12:17] ::1:51380 - "GET /api/v1/collections/test_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[31mERROR[0m:    [10-06-2024 22:12:46] Input is a zero-length, empty document: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 852, in get
    await to_thread.run_sync(
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 831, in process_get
    get = GetEmbedding.model_validate(orjson.loads(raw_body))
                                      ^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)
[32mINFO[0m:     [10-06-2024 22:12:46] ::1:51380 - "POST /api/v1/collections/test_collection/get HTTP/1.1" 500
[32mINFO[0m:     [10-06-2024 22:21:43] ::1:47170 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:21:43] ::1:47170 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:21:43] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 22:21:43] ::1:47186 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:21:45] ::1:47186 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:21:45] ::1:47186 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 22:22:39] ::1:56794 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:22:39] ::1:56794 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:22:39] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 22:22:39] ::1:56800 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:22:42] ::1:56800 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:22:42] ::1:56800 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 22:23:38] ::1:46274 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:23:38] ::1:46274 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:23:38] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 22:23:38] ::1:46276 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:23:41] ::1:46276 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:23:41] ::1:46276 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 22:23:52] ::1:55164 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:23:52] ::1:55164 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:23:52] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 22:23:52] ::1:55168 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:23:55] ::1:55168 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [10-06-2024 22:23:55] Insert of existing embedding ID: 1111
[33mWARNING[0m:  [10-06-2024 22:23:55] Add of existing embedding ID: 1111
[32mINFO[0m:     [10-06-2024 22:23:55] ::1:55168 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 22:23:55] ::1:55168 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/get HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:26:41] ::1:55102 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:26:41] ::1:55102 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:26:41] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 22:26:41] ::1:55108 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:26:44] ::1:55108 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [10-06-2024 22:26:44] Insert of existing embedding ID: 1111
[33mWARNING[0m:  [10-06-2024 22:26:44] Add of existing embedding ID: 1111
[32mINFO[0m:     [10-06-2024 22:26:44] ::1:55108 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 22:26:44] ::1:55108 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/get HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:27:59] ::1:41040 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:27:59] ::1:41040 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:27:59] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 22:27:59] ::1:41054 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:34:53] ::1:41124 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:34:53] ::1:41124 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:34:53] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 22:34:53] ::1:41138 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:34:56] ::1:41138 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [10-06-2024 22:34:56] Insert of existing embedding ID: 1111
[33mWARNING[0m:  [10-06-2024 22:34:56] Add of existing embedding ID: 1111
[32mINFO[0m:     [10-06-2024 22:34:56] ::1:41138 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 22:34:56] ::1:41138 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/get HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:35:18] ::1:58574 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:35:18] ::1:58574 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:35:18] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 22:35:18] ::1:58578 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:35:21] ::1:58578 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [10-06-2024 22:35:21] Insert of existing embedding ID: 1111
[33mWARNING[0m:  [10-06-2024 22:35:21] Add of existing embedding ID: 1111
[32mINFO[0m:     [10-06-2024 22:35:21] ::1:58578 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 22:35:21] ::1:58578 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/get HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:37:57] ::1:59304 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:37:57] ::1:59304 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:37:57] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 22:37:57] ::1:59306 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:38:50] ::1:52466 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:38:50] ::1:52466 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:38:50] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 22:38:50] ::1:52478 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:38:53] ::1:52478 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [10-06-2024 22:38:53] Insert of existing embedding ID: 1111
[33mWARNING[0m:  [10-06-2024 22:38:53] Add of existing embedding ID: 1111
[32mINFO[0m:     [10-06-2024 22:38:53] ::1:52478 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 22:38:53] ::1:52478 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/get HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:39:16] ::1:40252 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:39:16] ::1:40252 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:39:16] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 22:39:16] ::1:40262 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:39:19] ::1:40262 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [10-06-2024 22:39:19] Insert of existing embedding ID: 1111
[33mWARNING[0m:  [10-06-2024 22:39:19] Add of existing embedding ID: 1111
[32mINFO[0m:     [10-06-2024 22:39:19] ::1:40262 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 22:39:19] ::1:40262 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/get HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:39:33] ::1:35416 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:39:33] ::1:35416 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:39:33] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 22:39:33] ::1:35424 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:39:35] ::1:35424 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [10-06-2024 22:39:35] Insert of existing embedding ID: 1111
[33mWARNING[0m:  [10-06-2024 22:39:35] Add of existing embedding ID: 1111
[32mINFO[0m:     [10-06-2024 22:39:35] ::1:35424 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 22:39:35] ::1:35424 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/get HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:56:20] ::1:37086 - "GET /api/v1/heartbeat HTTP/1.1" 200
[31mERROR[0m:    [10-06-2024 22:56:37] Database test_database not found for tenant default_tenant
Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 471, in get_database
    await to_thread.run_sync(
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 143, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/api/segment.py", line 131, in get_database
    return self._sysdb.get_database(name=name, tenant=tenant)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/db/mixins/sysdb.py", line 95, in get_database
    raise NotFoundError(f"Database {name} not found for tenant {tenant}")
chromadb.db.base.NotFoundError: Database test_database not found for tenant default_tenant
[32mINFO[0m:     [10-06-2024 22:56:37] ::1:37086 - "GET /api/v1/databases/test_database?tenant=default_tenant HTTP/1.1" 500
[32mINFO[0m:     [10-06-2024 22:57:24] ::1:56008 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 22:57:51] ::1:56008 - "GET /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[31mERROR[0m:    [10-06-2024 22:58:05] Input is a zero-length, empty document: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 630, in create_collection
    await to_thread.run_sync(
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 606, in process_create_collection
    create = CreateCollection.model_validate(orjson.loads(raw_body))
                                             ^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)
[32mINFO[0m:     [10-06-2024 22:58:05] ::1:56008 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 500
[32mINFO[0m:     [10-06-2024 22:58:22] ::1:56008 - "GET /api/v1/count_collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[31mERROR[0m:    [10-06-2024 22:59:12] Input is a zero-length, empty document: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 852, in get
    await to_thread.run_sync(
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 831, in process_get
    get = GetEmbedding.model_validate(orjson.loads(raw_body))
                                      ^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)
[32mINFO[0m:     [10-06-2024 22:59:12] ::1:49330 - "POST /api/v1/collections/test_collection/get HTTP/1.1" 500
[31mERROR[0m:    [10-06-2024 22:59:17] Input is a zero-length, empty document: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 852, in get
    await to_thread.run_sync(
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 831, in process_get
    get = GetEmbedding.model_validate(orjson.loads(raw_body))
                                      ^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)
[32mINFO[0m:     [10-06-2024 22:59:17] ::1:49330 - "POST /api/v1/collections/36025c77-4d27-426b-9c6c-cecbddf4264b/get HTTP/1.1" 500
[31mERROR[0m:    [10-06-2024 22:59:36] Input is a zero-length, empty document: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 852, in get
    await to_thread.run_sync(
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 831, in process_get
    get = GetEmbedding.model_validate(orjson.loads(raw_body))
                                      ^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)
[32mINFO[0m:     [10-06-2024 22:59:36] ::1:49330 - "POST /api/v1/collections/my_collection/get HTTP/1.1" 500
[32mINFO[0m:     [10-06-2024 22:59:47] ::1:49330 - "GET /api/v1/collections/36025c77-4d27-426b-9c6c-cecbddf4264b/count HTTP/1.1" 200
[31mERROR[0m:    [10-06-2024 23:00:03] Input is a zero-length, empty document: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 961, in get_nearest_neighbors
    await to_thread.run_sync(
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 940, in process_query
    query = QueryEmbedding.model_validate(orjson.loads(raw_body))
                                          ^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)
[32mINFO[0m:     [10-06-2024 23:00:03] ::1:49330 - "POST /api/v1/collections/36025c77-4d27-426b-9c6c-cecbddf4264b/query HTTP/1.1" 500
[31mERROR[0m:    [10-06-2024 23:00:12] Input is a zero-length, empty document: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 961, in get_nearest_neighbors
    await to_thread.run_sync(
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 940, in process_query
    query = QueryEmbedding.model_validate(orjson.loads(raw_body))
                                          ^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)
[32mINFO[0m:     [10-06-2024 23:00:12] ::1:49330 - "POST /api/v1/collections/test_collection/query HTTP/1.1" 500
[32mINFO[0m:     [10-06-2024 23:00:22] ::1:49330 - "GET /api/v1/collections/test_collection?tenant=default_tenant&database=default_database HTTP/1.1" 200
[31mERROR[0m:    [10-06-2024 23:00:38] Input is a zero-length, empty document: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 97, in receive
    return self.receive_nowait()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 92, in receive_nowait
    raise WouldBlock
anyio.WouldBlock

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 159, in call_next
    message = await recv_stream.receive()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/streams/memory.py", line 112, in receive
    raise EndOfStream
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 78, in catch_exceptions_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 189, in __call__
    with collapse_excgroups():
  File "/usr/lib64/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_utils.py", line 93, in collapse_excgroups
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 191, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 92, in check_http_version_middleware
    return await call_next(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 165, in call_next
    raise app_exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/base.py", line 151, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/vinay/.local/lib/python3.12/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/telemetry/opentelemetry/__init__.py", line 130, in wrapper
    return await f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 700, in update_collection
    await to_thread.run_sync(
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vinay/.local/lib/python3.12/site-packages/chromadb/server/fastapi/__init__.py", line 686, in process_update_collection
    update = UpdateCollection.model_validate(orjson.loads(raw_body))
                                             ^^^^^^^^^^^^^^^^^^^^^^
orjson.JSONDecodeError: Input is a zero-length, empty document: line 1 column 1 (char 0)
[32mINFO[0m:     [10-06-2024 23:00:38] ::1:49330 - "PUT /api/v1/collections/36025c77-4d27-426b-9c6c-cecbddf4264b HTTP/1.1" 500
[32mINFO[0m:     [10-06-2024 23:01:18] ::1:43932 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:01:18] ::1:43932 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:01:18] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 23:01:18] ::1:43946 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:01:21] ::1:43946 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [10-06-2024 23:01:21] Insert of existing embedding ID: 1111
[33mWARNING[0m:  [10-06-2024 23:01:21] Add of existing embedding ID: 1111
[32mINFO[0m:     [10-06-2024 23:01:21] ::1:43946 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 23:01:21] ::1:43946 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/get HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:01:36] ::1:54226 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:01:36] ::1:54226 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:01:36] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 23:01:36] ::1:54240 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:04:22] ::1:60530 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:04:22] ::1:60530 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:04:22] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 23:04:22] ::1:60532 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:04:25] ::1:60532 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [10-06-2024 23:04:25] Insert of existing embedding ID: 1111
[33mWARNING[0m:  [10-06-2024 23:04:25] Add of existing embedding ID: 1111
[32mINFO[0m:     [10-06-2024 23:04:25] ::1:60532 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 23:04:25] ::1:60532 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/get HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:17:53] ::1:51556 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:17:53] ::1:51556 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:17:53] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 23:17:53] ::1:51568 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:18:00] ::1:51568 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [10-06-2024 23:18:00] Insert of existing embedding ID: 1111
[33mWARNING[0m:  [10-06-2024 23:18:00] Add of existing embedding ID: 1111
[32mINFO[0m:     [10-06-2024 23:18:00] ::1:51568 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 23:18:00] ::1:51568 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/get HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:21:31] ::1:56300 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:21:31] ::1:56300 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:21:31] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 23:21:31] ::1:56304 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:21:45] ::1:56304 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[33mWARNING[0m:  [10-06-2024 23:21:45] Insert of existing embedding ID: 1111
[33mWARNING[0m:  [10-06-2024 23:21:45] Add of existing embedding ID: 1111
[32mINFO[0m:     [10-06-2024 23:21:45] ::1:56304 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 23:21:45] ::1:56304 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/get HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:28:19] ::1:43632 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:28:19] ::1:43632 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:28:19] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 23:28:19] ::1:43640 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:28:42] Backing off send_request(...) for 0.1s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe7f0e64bc0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
[32mINFO[0m:     [10-06-2024 23:28:42] Backing off send_request(...) for 0.8s (requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us-api.i.posthog.com', port=443): Max retries exceeded with url: /batch/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe7f0c8cb60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')))
[32mINFO[0m:     [10-06-2024 23:34:40] ::1:55778 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:34:40] ::1:55778 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:34:40] Collection my_collection is not created.
[32mINFO[0m:     [10-06-2024 23:34:40] ::1:55786 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:34:46] ::1:55786 - "GET /api/v1/pre-flight-checks HTTP/1.1" 200
[32mINFO[0m:     [10-06-2024 23:34:46] ::1:55786 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/add HTTP/1.1" 201
[32mINFO[0m:     [10-06-2024 23:34:46] ::1:55786 - "POST /api/v1/collections/3ddebebd-0d42-4f11-af89-e3e722ad8885/get HTTP/1.1" 200
[33mWARNING[0m:  [02-07-2024 18:36:52] chroma_server_nofile is set to 65535, but this is less than current soft limit of 524288. chroma_server_nofile will not be set.
[32mINFO[0m:     [02-07-2024 18:36:53] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [02-07-2024 18:36:53] Starting component System
[36mDEBUG[0m:    [02-07-2024 18:36:53] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [02-07-2024 18:36:53] Starting component SqliteDB
[36mDEBUG[0m:    [02-07-2024 18:36:53] Starting component QuotaEnforcer
[36mDEBUG[0m:    [02-07-2024 18:36:53] Starting component Posthog
[36mDEBUG[0m:    [02-07-2024 18:36:53] Starting component LocalSegmentManager
[36mDEBUG[0m:    [02-07-2024 18:36:53] Starting component SegmentAPI
[32mINFO[0m:     [02-07-2024 18:36:53] Started server process [[36m206926[0m]
[32mINFO[0m:     [02-07-2024 18:36:53] Waiting for application startup.
[32mINFO[0m:     [02-07-2024 18:36:53] Application startup complete.
[32mINFO[0m:     [02-07-2024 18:36:53] Uvicorn running on [1mhttp://localhost:3000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [02-07-2024 18:38:04] ::1:60822 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [02-07-2024 18:38:04] ::1:60822 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [02-07-2024 18:38:04] ::1:60824 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [02-07-2024 18:38:38] ::1:46304 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [02-07-2024 18:38:38] ::1:46304 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [02-07-2024 18:38:38] Collection timepass_conversations10 is not created.
[32mINFO[0m:     [02-07-2024 18:38:38] ::1:46310 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [02-07-2024 18:38:57] ::1:60944 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [02-07-2024 18:38:57] ::1:60944 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [02-07-2024 18:38:57] Collection timepass_conversations10 is not created.
[32mINFO[0m:     [02-07-2024 18:38:57] ::1:60950 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [02-07-2024 18:39:55] ::1:55544 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [02-07-2024 18:39:55] ::1:55544 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [02-07-2024 18:39:55] Collection timepass_conversations10 is not created.
[32mINFO[0m:     [02-07-2024 18:39:55] ::1:55552 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[33mWARNING[0m:  [04-07-2024 20:28:08] chroma_server_nofile is set to 65535, but this is less than current soft limit of 524288. chroma_server_nofile will not be set.
[32mINFO[0m:     [04-07-2024 20:28:09] Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
[36mDEBUG[0m:    [04-07-2024 20:28:09] Starting component System
[36mDEBUG[0m:    [04-07-2024 20:28:09] Starting component OpenTelemetryClient
[36mDEBUG[0m:    [04-07-2024 20:28:09] Starting component SqliteDB
[36mDEBUG[0m:    [04-07-2024 20:28:09] Starting component QuotaEnforcer
[36mDEBUG[0m:    [04-07-2024 20:28:09] Starting component Posthog
[36mDEBUG[0m:    [04-07-2024 20:28:09] Starting component LocalSegmentManager
[36mDEBUG[0m:    [04-07-2024 20:28:09] Starting component SegmentAPI
[32mINFO[0m:     [04-07-2024 20:28:09] Started server process [[36m976311[0m]
[32mINFO[0m:     [04-07-2024 20:28:09] Waiting for application startup.
[32mINFO[0m:     [04-07-2024 20:28:09] Application startup complete.
[32mINFO[0m:     [04-07-2024 20:28:09] Uvicorn running on [1mhttp://localhost:3000[0m (Press CTRL+C to quit)
[32mINFO[0m:     [04-07-2024 20:31:26] ::1:60990 - "GET / HTTP/1.1" 404
[32mINFO[0m:     [04-07-2024 20:32:10] ::1:34932 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:32:10] ::1:34932 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:32:10] Collection timepass_conversations10 is not created.
[32mINFO[0m:     [04-07-2024 20:32:10] ::1:34934 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:32:20] ::1:33662 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:32:20] ::1:33662 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:32:20] Collection timepass_conversations10 is not created.
[32mINFO[0m:     [04-07-2024 20:32:20] ::1:33666 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:32:51] ::1:58232 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:32:51] ::1:58232 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:34:15] ::1:36054 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:34:15] ::1:36054 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:34:15] Collection timepass_conversations10 is not created.
[32mINFO[0m:     [04-07-2024 20:34:15] ::1:36066 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:36:10] ::1:57752 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:36:10] ::1:57752 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:36:10] Collection timepass_conversations10 is not created.
[32mINFO[0m:     [04-07-2024 20:36:10] ::1:57766 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:37:26] ::1:56050 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:37:26] ::1:56050 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:37:26] Collection timepass_conversations10 is not created.
[32mINFO[0m:     [04-07-2024 20:37:26] ::1:56062 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:37:41] ::1:56080 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:37:41] ::1:56080 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:37:41] Collection timepass_conversations10 is not created.
[32mINFO[0m:     [04-07-2024 20:37:41] ::1:56094 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:39:23] ::1:47402 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:39:23] ::1:47402 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 20:39:23] Collection timepass_conversations10 is not created.
[32mINFO[0m:     [04-07-2024 20:39:23] ::1:47408 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 22:13:11] ::1:33874 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 22:13:11] ::1:33874 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 22:13:11] Collection timepass_conversations10 is not created.
[32mINFO[0m:     [04-07-2024 22:13:11] ::1:33876 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 22:16:41] ::1:43554 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 22:16:41] ::1:43554 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 22:16:41] Collection timepass_conversations10 is not created.
[32mINFO[0m:     [04-07-2024 22:16:41] ::1:43562 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 23:53:58] ::1:42346 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 23:53:58] ::1:42346 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 23:53:58] Collection timepass_conversations10 is not created.
[32mINFO[0m:     [04-07-2024 23:53:58] ::1:42360 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 23:56:03] ::1:60240 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 23:56:03] ::1:60240 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 23:56:03] Collection timepass_conversations10 is not created.
[32mINFO[0m:     [04-07-2024 23:56:03] ::1:60244 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 23:56:35] ::1:42008 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 23:56:35] ::1:42008 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 23:56:35] Collection timepass_conversations10 is not created.
[32mINFO[0m:     [04-07-2024 23:56:35] ::1:42020 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 23:58:59] ::1:44994 - "GET /api/v1/tenants/default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 23:58:59] ::1:44994 - "GET /api/v1/databases/default_database?tenant=default_tenant HTTP/1.1" 200
[32mINFO[0m:     [04-07-2024 23:58:59] Collection timepass_conversations10 is not created.
[32mINFO[0m:     [04-07-2024 23:58:59] ::1:44996 - "POST /api/v1/collections?tenant=default_tenant&database=default_database HTTP/1.1" 200
